server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/musicstream
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classPath:db/changelog.yml